# Generated by Django 4.0.3 on 2022-03-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField()),
                ('muestra', models.IntegerField()),
                ('g', models.IntegerField()),
                ('k', models.IntegerField()),
                ('c', models.IntegerField()),
                ('method', models.CharField(choices=[('lineal', 'Congruencial Lineal'), ('multiplicativo', 'Congruencial Multiplicativo'), ('lenguaje', 'Provisto por lenguaje')], max_length=100)),
                ('intervalos', models.CharField(choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RandomNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
            ],
        ),
    ]
