# Generated by Django 4.0.3 on 2022-03-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP', '0002_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='graph',
            field=models.ImageField(upload_to='media'),
        ),
    ]
