# Generated by Django 4.0.3 on 2022-03-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP', '0003_alter_graph_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomnumber',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
