# Generated by Django 4.0.3 on 2022-03-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TP', '0004_randomnumber_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomnumber',
            name='index',
        ),
    ]
