# Generated by Django 4.0.3 on 2022-03-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP', '0006_randomnumber_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='graph',
            field=models.CharField(max_length=100000000),
        ),
    ]
