# Generated by Django 4.0.3 on 2022-03-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP', '0007_alter_graph_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiCuadrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.CharField(max_length=100)),
                ('fo', models.IntegerField()),
                ('fe', models.IntegerField()),
                ('c', models.FloatField()),
                ('c_acumulado', models.FloatField()),
            ],
        ),
    ]
