# Generated by Django 4.0.3 on 2022-03-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP', '0008_chicuadrado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.AlterField(
            model_name='chicuadrado',
            name='c',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chicuadrado',
            name='c_acumulado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chicuadrado',
            name='fe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chicuadrado',
            name='fo',
            field=models.CharField(max_length=100),
        ),
    ]
